# Generated by Django 4.1.3 on 2022-12-04 13:01

import django.core.validators
from django.db import migrations, models

import characters.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "csv",
                    models.FileField(
                        upload_to=characters.models.upload_csv,
                        validators=[
                            django.core.validators.FileExtensionValidator(["csv"])
                        ],
                    ),
                ),
            ],
        ),
    ]
